---
#services: docker
os: linux
dist: trusty
sudo: required
language: python

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    DCS: etcd

install:
  - sudo pip install setuptools docker-compose yamllint ansible==${ANSIBLE_VERSION} --upgrade -q > /dev/null
  - docker-compose -f tests/${DISTRIBUTION}-${DISTRIBUTION_VERSION}-compose.yml -f tests/${DCS}-compose.yml up -d
  - docker ps -a

script:
#  - find . -name "*.yml" -type f | xargs yamllint
  - ansible-galaxy install -r tests/requirements.yml
  - ansible-playbook -i tests/hosts tests/patroni.yml --syntax-check
  - ansible-playbook -i tests/hosts tests/patroni.yml -Dvv --limit ${DISTRIBUTION}-${DISTRIBUTION_VERSION} --extra-vars patroni_dcs=${DCS}
