---
#services: docker

#sudo: required

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    DCS: etcd

before_install:
#  - sudo apt-get -qq update -y && sudo apt-get -qq install libffi-dev libssl-dev python-pip -y > /dev/null && sudo pip -q install setuptools docker-compose ansible --upgrade
  - |
    sudo apt-get -qq update -y && \
    apt-get -qq install python-pip -y > /dev/null && \
    pip install setuptools docker-compose ansible yamllint --upgrade -q > /dev/null
install:
  - docker-compose -f tests/${DISTRIBUTION}-${DISTRIBUTION_VERSION}-compose.yml -f tests/${DCS}-compose.yml up -d
  - sleep 5
  - docker ps -a
script:
#  - yamllint 
  - ansible-playbook -i hosts tests/test.yml --syntax-check
  - ansible-playbook -i hosts tests/test.yml -Dvv --limit ${DISTRIBUTION}-${DISTRIBUTION_VERSION} --extra-vars patroni_dcs=${DCS}
