---
sudo: required

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    PACKAGE_MANAGER: apt
    DOCKER_INIT: /lib/systemd/systemd
    DCS: etcd

before_install:
  - sudo apt-get -qq update -y && sudo apt-get -qq install libffi-dev libssl-dev python3-pip -y > /dev/null && sudo pip -q install setuptools docker-compose ansible --upgrade
install:
  - docker-compose -f tests/${DCS}-compose.yml -f tests/${DISTRIBUTION}-${DISTRIBUTION_VERSION}-compose.yml up -d
script:
  - docker ps
  - python --version
  - pip --version

