---

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4.0.0

before_install:
  - docker run -d -v "${PWD}/tests":/tmp/tests --name="${DISTRIBUTION}-${DISTRIBUTION_VERSION}" --privileged ${DISTRIBUTION}:${DISTRIBUTION_VERSION} /lib/systemd/systemd
  - sleep 1
  - docker ps -a

install:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt update -qq && apt install python-pip git -y -qq && pip install --upgrade pip && pip install ansible==${ANSIBLE_VERSION} ansible-lint"
# Workaround to fix "Failed to find required executable modprobe in paths" while adding softdog kernel module for watchdog
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "apt install --reinstall linux-image-`uname -r` -qq -y"
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "python --version; ansible --version"

script:
  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-galaxy install -r /tmp/tests/requirements.yml"

# - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-lint /tmp/tests/test.yml"

  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-playbook -i /tmp/tests/inventory /tmp/tests/test.yml --syntax-check"

  - docker exec -t ${DISTRIBUTION}-${DISTRIBUTION_VERSION} /bin/sh -c "ansible-playbook -i /tmp/tests/inventory /tmp/tests/test.yml -Dvv"

  - docker rm -f ${DISTRIBUTION}-${DISTRIBUTION_VERSION}
