---
sudo: required

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    PACKAGE_MANAGER: apt
    DOCKER_INIT: /lib/systemd/systemd
    DCS: etcd

before_install:
  - apt-get -qq update -y && apt-get -qq install python-pip docker-compose -y && pip -q install setuptools ansible --upgrade