---
sudo: required

services: docker

env:
  - DISTRIBUTION: ubuntu
    DISTRIBUTION_VERSION: 16.04
    ANSIBLE_VERSION: 2.4
    PACKAGE_MANAGER: apt
    DOCKER_INIT: /lib/systemd/systemd
    DCS: etcd

before_install:
  - sudo apt-get -qq update -y && sudo apt-get -qq install libffi-dev libssl-dev python3-pip -y && sudo pip -q install setuptools docker-compose ansible --upgrade