---

- name: Install apt packages
  apt:
    pkg: "{{ item.pkg }}"
    state: "{{ item.state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - { pkg: "python-pip",      state: "present" }
    - { pkg: "jq",              state: "present" }

- name: Install patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "setuptools", state: "latest" }
    - { name: "patroni",    state: "present" }
