---

- name: Install apt packages
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - "{{ patroni_pkg_dependencies }}"
  when: ansible_os_family == "Debian"

- name: Install rpm packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ patroni_pkg_dependencies }}"
  when: ansible_os_family == "RedHat"

- name: Install patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: "setuptools", state: "latest" }
    - { name: "patroni",    state: "present" }
