---

- block:
    - name: Configure PostgreSQL APT key
      apt_key: 
        url: "{{ postgresql_apt_key_url }}" 
        state: present

    - name: Configure PostgreSQL APT repository
      apt_repository: 
        repo: "{{ postgresql_apt_repo }}"
        state: present

    - name: Install apt packages
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        update_cache: yes
        cache_valid_time: 600
      with_items:
        - "{{ patroni_pkg_dependencies }}"
  when: ansible_os_family == "Debian"

- name: Install rpm packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ patroni_pkg_dependencies }}"
  when: ansible_os_family == "RedHat"

- include: watchdog.yml
  when: patroni_watchdog_mode in ('automatic', 'required')

- name: Install patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    umask: "0022"
  with_items:
    - { name: "setuptools", state: "latest" }
    - { name: "patroni[{{ patroni_dcs }}]",    state: "present" }
