---

- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: [patroni, patroni-install, patroni-configure]

- include: install.yml
  tags: [patroni, patroni-install]

- include: configure.yml
  tags: [patroni, patroni-configure]

- name: Ensure patroni is running
  service:
    name: patroni
    state: started
    enabled: yes
  tags: [patroni]
