---

- name: Install watchdog
  package:
    name: watchdog
    update_cache: yes

- name: Add the softdog kernel module
  modprobe:
    name: softdog

- name: Change device permissions
  file:
    path: /dev/watchdog
    state: file
    owner: "{{ patroni_system_user }}"
    group: "{{ patroni_system_group }}"

- name: Ensure watchdog is running
  service:
    name: watchdog
    enabled: yes
    state: started
